name: versioning

on:
  workflow_run:
    workflows: ["test"]
    types: [completed]
    branches:
      - "main"

jobs:
  semantic-versioning:
    if: github.event.workflow_run.conclusion == 'success'
    name: Semantic Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_created: ${{ steps.semantic_release_step.outputs.new_release_published }}
      release_version: ${{ steps.semantic_release_step.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        id: semantic_release_step
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 20
          extra_plugins: |
            @semantic-release/github@8
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
